
empty_classic_maze = [
    "o---o---o---o---o---o---o---o---o---o---o---o---o---o---o---o---o",
    "|                                                               |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "|                                                               |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "|                                                               |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "|                                                               |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "|                                                               |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "|                                                               |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "|                                                               |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "|                             G   G                             |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "|                             G   G                             |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "|                                                               |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "|                                                               |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "|                                                               |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "|                                                               |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "|                                                               |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "|                                                               |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o",
    "| S |                                                           |",
    "o---o---o---o---o---o---o---o---o---o---o---o---o---o---o---o---o",
]

all_japan_2007 = [
    "o---o---o---o---o---o---o---o---o---o---o---o---o---o---o---o---o",
    "|                                                               |",
    "o   o---o---o---o---o---o---o---o---o---o---o---o---o---o---o   o",
    "|   |       |       |                                           |",
    "o   o   o   o   o   o   o---o---o---o---o---o---o   o---o   o   o",
    "|       |       |       |                   |       |       |   |",
    "o---o   o---o---o---o---o   o---o---o---o   o   o---o   o---o   o",
    "|           |   |   |   |       |       |       |       |   |   |",
    "o---o---o   o   o   o   o---o   o   o   o   o---o   o---o   o   o",
    "|       |   |               |   |   |   |   |       |       |   |",
    "o   o   o   o   o   o   o   o   o   o   o   o   o---o   o   o   o",
    "|   |   |   |   |   |   |       |   |   |   |   |       |   |   |",
    "o   o   o   o   o---o---o---o---o   o   o   o   o   o---o   o   o",
    "|   |       |   |                   |       |       |       |   |",
    "o   o---o---o   o   o---o---o---o---o---o---o---o---o   o---o   o",
    "|           |   |   |       | G   G |   |   |   |       |       |",
    "o---o   o   o   o   o   o   o   o   o   o   o   o   o---o   o   o",
    "|       |   |   |       |   | G   G             |   |       |   |",
    "o   o---o   o   o---o   o   o---o---o   o---o   o   o   o---o   o",
    "|       |   |       |   |       |   |       |   |   |       |   |",
    "o---o   o   o---o   o---o   o---o   o---o   o   o   o---o   o   o",
    "|       |       |                       |   |   |   |       |   |",
    "o   o---o---o   o   o   o---o---o   o   o   o   o   o   o---o   o",
    "|       |   |   |   |           |   |   |   |       |       |   |",
    "o---o   o   o   o---o---o---o   o---o   o   o   o---o---o   o   o",
    "|       |       |   |   |   |       |   |   |               |   |",
    "o   o---o   o---o   o   o   o---o   o   o   o---o---o---o---o   o",
    "|   |       |                   |   |   |                   |   |",
    "o   o   o   o   o   o   o   o   o   o   o---o---o---o---o   o   o",
    "|       |       |   |   |   |       |   |                   |   |",
    "o   o   o   o   o   o   o   o---o   o   o   o---o---o---o---o   o",
    "| S |       |                           |                       |",
    "o---o---o---o---o---o---o---o---o---o---o---o---o---o---o---o---o",
]
